version: '3'

services:

  nginx:
      build: 
        context: ./nginx
        dockerfile: Dockerfile.prod
      image: raphaelvasques/nginx-node
      container_name: nginx
      tty: true
      networks:
        - node-network
      ports:
        - "8080:80"

  node:
    build: 
      context: ./node
    image: raphaelvasques/node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s docker-entrypoint.sh
    command: node index.js 
    networks:
      - node-network
    tty: true
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./resources/sqlini.sql:/docker-entrypoint-initdb.d/zzz-init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge